# Generated by Django 4.2.7 on 2023-11-25 23:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{11}$')])),
                ('email', models.EmailField(max_length=255)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Зарегестрированно'), ('ACCEPTED', 'Принято'), ('IN PROGRESS', 'На рассмотрении'), ('CONFIRMED', 'Подтверждено'), ('REJECTED', 'Отклонено')], default='NULL', max_length=100)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.addressservice')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Moderators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('options', models.CharField(choices=[('Option1', 'Вариант 1'), ('Option2', 'Вариант 2'), ('Option3', 'Вариант 3')], default='Option1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.moderators')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.moderators')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.service')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.categories')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.polls')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.posts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='AppealAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=None)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('appeal_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.appeal')),
                ('from_service_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.service')),
                ('to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.users')),
            ],
        ),
        migrations.AddField(
            model_name='appeal',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.moderators'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.users'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.categories'),
        ),
        migrations.AddField(
            model_name='addressservice',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.categories'),
        ),
        migrations.AddField(
            model_name='addressservice',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.service'),
        ),
    ]
